example:
  property: "This is default property"
server:
  port: 9000

spring:
  cloud:
    # 消息队列配置
    stream:
      bindings:
        inBoundFS:
          destination: testTopic          # 消息队列名称
          content-type: application/json  # 消息类型
          group: filesharingGroup         # 消费者组的名称，保证服务实例中只有一个处理消息
      kafka:
        binder:
          # Kafka 和 ZooKeeper 的地址
          zkNodes: ping.qixqi.cn:2181
          brokers: ping.qixqi.cn:9092
          required-acks: 1


# Eureka 服务发现
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

# 设置日志级别
logging:
  level:
    cn.qixqi.pan: DEBUG