server:
  port: 9411

# 不加报错：Prometheus requires that all meters with the same name have the same set of tag keys
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  # Spring Actuator
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

