example:
  property: "This is default property"

server:
  servlet:
    context-path: /auth
  port: 8901

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

# Eureka 服务发现
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# JWT 令牌密钥
jwt:
  signing:
    key: "345345fsdgsf5345"