example:
  property: "This is default property"
spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"

  datasource:
    url: "jdbc:mysql://ping.qixqi.cn:3306/pan?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    username: "root"
    password: "1214"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"
    initialization-mode: never

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

# Eureka 服务发现
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Spring Security
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/auth/user

# JWT 令牌密钥
jwt:
  signing:
    key: "345345fsdgsf5345"
