example:
  property: "This is default property"
server:
  port: 9090
# mongo3.0 以上，host和port配置不支持，必须使用uri配置所有信息
spring:
  data:
    mongodb:
      uri: mongodb://admin:1214@ping.qixqi.cn:27017/pan?authSource=admin
# 是否初始化 mongodb
# TODO: 初始化时，删除以前的数据
db:
  mongodb:
    rebuild: false
    init:
      file: "file.json"
      folder_link: "folder_link.json"

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

# Eureka 服务发现
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
