example:
  property: "This is default property"
server:
  port: 9090
# mongo3.0 以上，host和port配置不支持，必须使用uri配置所有信息
spring:
  data:
    mongodb:
      uri: mongodb://admin:1214@ping.qixqi.cn:27017/pan?authSource=admin
  # Spring Sleuth & Zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0    # 跟踪全部事务
  cloud:
    # 消息队列配置
    stream:
      bindings:
        outBoundFS:
          destination: testTopic          # 消息队列名称
          content-type: application/json  # 消息类型
      kafka:
        binder:
          # Kafka 和 ZooKeeper 的地址
          zkNodes: ping.qixqi.cn:2181
          brokers: ping.qixqi.cn:9092



# 是否初始化 mongodb
# TODO: 初始化时，删除以前的数据
db:
  mongodb:
    rebuild: false
    init:
      file: "file.json"
      folder_link: "folder_link.json"

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

# Eureka 服务发现
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 设置日志级别
logging:
  level:
    cn.qixqi.pan: DEBUG

# Redis
redis:
  server: ping.qixqi.cn
  port: 6379
  password: 1214

# UserContext
user-context:
  key:
    trace-id: "trace_id"
    auth-token: "auth_token"
    uid: "uid"
