server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/QIXQI/config-repo/
          search-paths: userservice, testservice, filesystemservice
          # username:         # 私有库
          # password:         # 私有库